//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Grammar/ETSL.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ETSLParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IETSLVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ETSLParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] ETSLParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ETSLParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] ETSLParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ETSLParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDecl([NotNull] ETSLParser.VarDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ETSLParser.funcDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncDecl([NotNull] ETSLParser.FuncDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ETSLParser.eventDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEventDecl([NotNull] ETSLParser.EventDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ETSLParser.agentDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAgentDecl([NotNull] ETSLParser.AgentDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ETSLParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamList([NotNull] ETSLParser.ParamListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ETSLParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam([NotNull] ETSLParser.ParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ETSLParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] ETSLParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ETSLParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlock([NotNull] ETSLParser.BlockContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BlockAction</c>
	/// labeled alternative in <see cref="ETSLParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBlockAction([NotNull] ETSLParser.BlockActionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>VarDeclAction</c>
	/// labeled alternative in <see cref="ETSLParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDeclAction([NotNull] ETSLParser.VarDeclActionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>LogAction</c>
	/// labeled alternative in <see cref="ETSLParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLogAction([NotNull] ETSLParser.LogActionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IfAction</c>
	/// labeled alternative in <see cref="ETSLParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfAction([NotNull] ETSLParser.IfActionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ReturnAction</c>
	/// labeled alternative in <see cref="ETSLParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnAction([NotNull] ETSLParser.ReturnActionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ExprAction</c>
	/// labeled alternative in <see cref="ETSLParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExprAction([NotNull] ETSLParser.ExprActionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>SkipAction</c>
	/// labeled alternative in <see cref="ETSLParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSkipAction([NotNull] ETSLParser.SkipActionContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>StringExpr</c>
	/// labeled alternative in <see cref="ETSLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStringExpr([NotNull] ETSLParser.StringExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>FloatExpr</c>
	/// labeled alternative in <see cref="ETSLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloatExpr([NotNull] ETSLParser.FloatExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>MulDivExpr</c>
	/// labeled alternative in <see cref="ETSLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMulDivExpr([NotNull] ETSLParser.MulDivExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IdExpr</c>
	/// labeled alternative in <see cref="ETSLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdExpr([NotNull] ETSLParser.IdExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CompareExpr</c>
	/// labeled alternative in <see cref="ETSLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompareExpr([NotNull] ETSLParser.CompareExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>CallExpr</c>
	/// labeled alternative in <see cref="ETSLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCallExpr([NotNull] ETSLParser.CallExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>IntExpr</c>
	/// labeled alternative in <see cref="ETSLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntExpr([NotNull] ETSLParser.IntExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>ParenExpr</c>
	/// labeled alternative in <see cref="ETSLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenExpr([NotNull] ETSLParser.ParenExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AddSubExpr</c>
	/// labeled alternative in <see cref="ETSLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAddSubExpr([NotNull] ETSLParser.AddSubExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>BooleanExpr</c>
	/// labeled alternative in <see cref="ETSLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBooleanExpr([NotNull] ETSLParser.BooleanExprContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>AssignExpr</c>
	/// labeled alternative in <see cref="ETSLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignExpr([NotNull] ETSLParser.AssignExprContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ETSLParser.argList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgList([NotNull] ETSLParser.ArgListContext context);
}
