//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Grammar/ETSL.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="ETSLParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IETSLListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ETSLParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] ETSLParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ETSLParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] ETSLParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ETSLParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] ETSLParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ETSLParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] ETSLParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ETSLParser.eventDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEventDecl([NotNull] ETSLParser.EventDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ETSLParser.eventDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEventDecl([NotNull] ETSLParser.EventDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ETSLParser.agentDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAgentDecl([NotNull] ETSLParser.AgentDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ETSLParser.agentDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAgentDecl([NotNull] ETSLParser.AgentDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ETSLParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamList([NotNull] ETSLParser.ParamListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ETSLParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamList([NotNull] ETSLParser.ParamListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ETSLParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam([NotNull] ETSLParser.ParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ETSLParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam([NotNull] ETSLParser.ParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ETSLParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] ETSLParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ETSLParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] ETSLParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ETSLParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAction([NotNull] ETSLParser.ActionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ETSLParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAction([NotNull] ETSLParser.ActionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="ETSLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] ETSLParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="ETSLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] ETSLParser.ExpressionContext context);
}
