//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./Grammar/ETSL.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IETSLListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class ETSLBaseListener : IETSLListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="ETSLParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] ETSLParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ETSLParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] ETSLParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ETSLParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] ETSLParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ETSLParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] ETSLParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ETSLParser.eventDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEventDecl([NotNull] ETSLParser.EventDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ETSLParser.eventDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEventDecl([NotNull] ETSLParser.EventDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ETSLParser.agentDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAgentDecl([NotNull] ETSLParser.AgentDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ETSLParser.agentDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAgentDecl([NotNull] ETSLParser.AgentDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ETSLParser.paramList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParamList([NotNull] ETSLParser.ParamListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ETSLParser.paramList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParamList([NotNull] ETSLParser.ParamListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ETSLParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParam([NotNull] ETSLParser.ParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ETSLParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParam([NotNull] ETSLParser.ParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ETSLParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] ETSLParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ETSLParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] ETSLParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ETSLParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAction([NotNull] ETSLParser.ActionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ETSLParser.action"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAction([NotNull] ETSLParser.ActionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="ETSLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] ETSLParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="ETSLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] ETSLParser.ExpressionContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
